maxNumCompThreads(8);
clear;
clc;

rootDir = fileparts(mfilename('fullpath'));
addpath(genpath(rootDir));
addpath(genpath(fullfile(rootDir, 'utils')));
addpath(genpath(fullfile(rootDir, 'measures')));

%% Parallel pool setup (reference: run_IMVC_CAH_ablation.m)
%if isempty(gcp('nocreate'))
%    try
%        parpool('local', 8);
%    catch
%        parpool('local');
%    end
%end
%poolobj = gcp('nocreate');
%if ~isempty(poolobj)
%    spmd
%        cd(rootDir);
%        addpath(genpath(rootDir));
%        maxNumCompThreads(1);
%    end
%end

datadir='../datasets/';
numname = {'_Per0.1','_Per0.3','_Per0.5','_Per0.7','_Per0.9'};

% Automatically find all datasets in datadir
files = dir([datadir, '*.mat']);
all_names = {files.name};
found_datasets = {};
for i = 1:length(all_names)
    fname = all_names{i};
    for j = 1:length(numname)
        suffix = [numname{j}, '.mat'];
        if length(fname) > length(suffix) && strcmp(fname(end-length(suffix)+1:end), suffix)
            found_datasets{end+1} = fname(1:end-length(suffix));
            break;
        end
    end
end
dataname = unique(found_datasets);
numdata = length(dataname);
fprintf('Found %d datasets to process.\n', numdata);

% Parameters Ranges for Grid Search
lambda_range = [0.01,0.1, 0.3, 1, 3, 10];
m_ratio_range = [5, 10,20,50,100,200]; % m = nCluster * ratio
k_range = [5,10,15];

% Fixed Parameters
param.maxIter = 5;
param.maxIterC = 10;

for iDataIdx = 1:length(dataname)
    % Check if results already exist
    saveName = sprintf('IMVC_CAH_%s_AllResults.mat', cell2mat(dataname(iDataIdx)));
    savePath = ['./results/', saveName];
    
    if exist(savePath, 'file')
        fprintf('>>> Skipping %s (Results already exist)\n', cell2mat(dataname(iDataIdx)));
        continue;
    end

    nSplits = length(numname);
    nfolds = 1; 
    
    % Initialize struct with specific field order for better readability
    All_Results = struct('Lambda', {}, 'm_Ratio', {}, 'k_Neighbor', {}, 'MissingRatio', {}, ...
                         'ACC', {}, 'NMI', {}, 'Purity', {}, 'AR', {}, 'RI', {}, ...
                         'MI', {}, 'HI', {}, 'Fscore', {}, 'Precision', {}, 'Recall', {}, ...
                         'CoreTime', {}, 'TotalTime', {}, 'Time', {});
    res_counter = 0;
    
    % Track Best Results for Convergence Plot
    % Best_Objs = cell(1, nSplits);
    Best_ACCs = -ones(1, nSplits);
    
    % --- Grid Search Loops ---
    for iSplit = 1:nSplits
        datafile = [datadir, cell2mat(dataname(iDataIdx)), cell2mat(numname(iSplit)), '.mat'];
        % fprintf('Loading %s...\n', datafile);
        load(datafile); 
        
        nCluster = length(unique(Y));
        nView = length(Xs);
        missInd = folds{1}; 
        
        % --- 1. Physical Filtering (Done once per split) ---
        Xs_filtered = cell(1, nView);
        for iView = 1:nView
            Xi = Xs{iView};
            % Note: Assuming Xs is d x N or N x d. 
            % If generated by generatenew.m, Xs is usually d x N.
            % missInd is N x nView.
            
            % Check dimensions
            if size(Xi, 2) ~= size(missInd, 1)
                    Xi = Xi'; % Transpose to d x N if needed
            end
            
            Xs_filtered{iView} = Xi(:, missInd(:,iView) > 0);
            Xs_filtered{iView} = Xs_filtered{iView}'; % Transpose to N_v x d for litekmeans
            Xs_filtered{iView} = double(zscore(double(Xs_filtered{iView})));
        end

        % --- Grid search in parallel (parfor over parameter combinations) ---
        total_combinations = length(lambda_range) * length(m_ratio_range) * length(k_range);
        param_combos = zeros(total_combinations, 3); % [lambda, m_ratio, k_neighbor]
        idx_combo = 0;
        for l_idx = 1:length(lambda_range)
            for mr_idx = 1:length(m_ratio_range)
                for k_idx = 1:length(k_range)
                    idx_combo = idx_combo + 1;
                    param_combos(idx_combo, :) = [lambda_range(l_idx), m_ratio_range(mr_idx), k_range(k_idx)];
                end
            end
        end

        all_metrics = zeros(total_combinations, 10); % my_eval_y returns 10 metrics
        all_times = zeros(total_combinations, 2); % [CoreTime, TotalTime]

        fprintf('>>> Running %s %s : %d combinations sequentially...\n', ...
            cell2mat(dataname(iDataIdx)), cell2mat(numname(iSplit)), total_combinations);

        for combo_idx = 1:total_combinations
            cur_lambda = param_combos(combo_idx, 1);
            cur_m_ratio = param_combos(combo_idx, 2);
            cur_k_neighbor = param_combos(combo_idx, 3);

            local_param = param;
            local_param.lambda = cur_lambda;

            rng(1, 'twister');

            % --- 2. Anchor Generation + Solver (Total Time) ---
            t_total_start = tic;
            
            Bs = cell(1, nView);
            m = nCluster * cur_m_ratio; % Dynamic m
            for iView = 1:nView
                n_samples = size(Xs_filtered{iView}, 1);
                if n_samples < m
                    Xa = Xs_filtered{iView};
                else
                    [~, Xa] = litekmeans(Xs_filtered{iView}, m, 'Replicates', 1);
                end
                Bs{iView} = ConstructBP_pkn(Xs_filtered{iView}, Xa, 'nNeighbor', cur_k_neighbor);
            end

            % --- 3. Run Solver (Core Time) ---
            t_core_start = tic;
            [y_pred, ~] = CARD_Solver_Z(Bs, missInd, nCluster, local_param);
            core_time = toc(t_core_start);
            total_time = toc(t_total_start);

            % --- 4. Evaluation ---
            result = my_eval_y(y_pred, Y);

            % Print each parameter combination result (order may vary due to parfor)
            % Print each parameter combination result (order may vary due to parfor)
            fprintf('   [%d/%d] Lambda=%.1f, m_ratio=%d, k=%d | ACC=%.4f | CoreT=%.2fs, TotalT=%.2fs\n', ...
                combo_idx, total_combinations, cur_lambda, cur_m_ratio, cur_k_neighbor, ...
                result(1), core_time, total_time);

            all_metrics(combo_idx, :) = result(:)';
            all_times(combo_idx, :) = [core_time, total_time];
        end

        % --- Store results sequentially (parfor cannot append to struct) ---
        str_ratio = cell2mat(numname(iSplit));
        miss_ratio_num = str2double(strrep(str_ratio, '_Per', ''));
        for combo_idx = 1:total_combinations
            cur_lambda = param_combos(combo_idx, 1);
            cur_m_ratio = param_combos(combo_idx, 2);
            cur_k_neighbor = param_combos(combo_idx, 3);
            result = all_metrics(combo_idx, :);
            runtime = all_times(combo_idx);

            res_counter = res_counter + 1;
            All_Results(res_counter).Lambda = cur_lambda;
            All_Results(res_counter).m_Ratio = cur_m_ratio;
            All_Results(res_counter).k_Neighbor = cur_k_neighbor;
            All_Results(res_counter).MissingRatio = miss_ratio_num;

            All_Results(res_counter).ACC = result(1);
            All_Results(res_counter).NMI = result(2);
            All_Results(res_counter).Purity = result(3);
            All_Results(res_counter).AR = result(4);
            All_Results(res_counter).RI = result(5);
            All_Results(res_counter).MI = result(6);
            All_Results(res_counter).HI = result(7);
            All_Results(res_counter).Fscore = result(8);
            All_Results(res_counter).Precision = result(9);
            All_Results(res_counter).Recall = result(10);
            All_Results(res_counter).CoreTime = all_times(combo_idx, 1);
            All_Results(res_counter).TotalTime = all_times(combo_idx, 2);
            All_Results(res_counter).Time = all_times(combo_idx, 2);
        end

        best_acc_split = max(all_metrics(:, 1));
        if best_acc_split > Best_ACCs(iSplit)
            Best_ACCs(iSplit) = best_acc_split;
        end
        fprintf('>>> Best ACC for %s: %.4f\n', str_ratio, best_acc_split);
    end
    
    % --- Plot Convergence for Best Results ---
    % plot_convergence(Best_Objs, numname, ['./results/Convergence_', cell2mat(dataname(iDataIdx)), '.png']);
    
    % --- Save ALL Results for this Dataset in ONE File ---
    if ~exist('./results', 'dir')
        mkdir('./results');
    end
    
    saveName = sprintf('IMVC_CAH_%s_AllResults.mat', cell2mat(dataname(iDataIdx)));
    savePath = ['./results/', saveName];
    
    save(savePath, 'All_Results'); 
    fprintf('=======================================================\n');
    fprintf('All results saved to %s\n', savePath);
    fprintf('Total combinations run: %d\n', res_counter);
    fprintf('=======================================================\n');
end
